spring:
  application:
    name: alert-service
  kafka:
    bootstrap-servers: localhost:9094

    consumer:
      group-id: alert-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring:
          json:
            type:
              mapping: "alertingEvent:com.prajwal.alert_service.kafka.Event.AlertingEvent"
  datasource:
    url: jdbc:mysql://localhost:3307/energy_tracker
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: none

  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false