spring:
  application:
    name: ingestion-service

  server:
    port: 8082

  kafka:
    bootstrap-servers: localhost:9094
    template:
      default-topic: energy-usage
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  simulation:
    endpoint: http://localhost:8082/ingestion
    request-perinterval: 1
    interval-ms: 50000
    parallel-threads: 5