spring:
  application:
    name: usage-service

  server:
    port: 8083

  Kafka:
    bootstrap-server:
      localhost: 9094
    consumer:
      group-id: usage-service
      key-deserialization: org.apache.kafka.common.serialization.StringDeserializer
      value-deserialization: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: energyUsageEvent:com.prajwal.kafka.event.EnergyUsageEvent

    template:
      default-topic: energy-alerts
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


influx:
  url: http://localhost:8072
  token: my-token
  org: prajwal
  bucket: usage-bucket

device:
  service:
    url: http://localhost:8081/api/v1/device

user:
  service:
    url: http://localhost:8080/api/v1/user




